### ISSUE TITLE
Demo page does not work in Safari

### ISSUE THREAD

**Issue by arve0** [Godofbrowser/vuejs-dialog#1]
Safari 10.1.2 gives the error

```
app.main.js:1071:84
TypeError: undefined is not an object (evaluating 'window.navigator.userLanguage[1]')
```

and a blank page. Works in Chrome.

**Comment by Godofbrowser** [comment]
@arve0 Thanks. Cross browser support is being added (here ca25a1a5475caa140934e4cac904d45ff4521397). Should work without errors now.
