### ISSUE TITLE
[feature request]can contents be a component?

### ISSUE THREAD

**Issue by hkuclion** [Godofbrowser/vuejs-dialog#13]
Currently only text and html can be message, can there be a chance that if type of message is object then message will be used as an component so that contents can also be reactive, or use a option to set the message to be treated as a component name?

**Comment by Godofbrowser** [comment]
I've been thinking around this.... and yes! i think it's possible. This should be the next feature to be implemented. Thanks for the idea...

**Comment by Dolu89** [comment]
Here is news about this feature ? I really need this too
Thanks

**Comment by Godofbrowser** [comment]
Thus Sunday... It'll be released

**Comment by Godofbrowser** [comment]
Please use custom component for this.
