### ISSUE TITLE
Can I customize the buttons, or add some other buttons, a third one, fourth...

### ISSUE THREAD

**Issue by danhe** [Godofbrowser/vuejs-dialog#14]
because of some raison, I want to have a confirm with three buttons, is this possible?

**Comment by Godofbrowser** [comment]
For now, it's not possible. But there will be similar solution soon

**Comment by Godofbrowser** [comment]
This feature will be possible with custom components once completed

![screenshot-localhost 9000-2018-03-23-05-14-11](https://user-images.githubusercontent.com/20337551/37811289-81221670-2e59-11e8-930c-b08a4cac9fd0.png)

**Comment by Cookizza** [comment]
Any update on this? This package provides a really nice dialog and if we could customise buttons somewhat, that would be awesome

**Comment by gmatkowski** [comment]
Any news about that ?
