### ISSUE TITLE
Add option to set a dialog title

### ISSUE THREAD

**Issue by nurbek-ab** [Godofbrowser/vuejs-dialog#15]
It would be great if you added an option to set a title for the dialogs.

**Comment by Godofbrowser** [comment]
Thanks for your suggestions/feature request. I will look into this.

**Comment by Godofbrowser** [comment]
Closing this cos the feature has been implemented. [b511287ca4ec0549927964460b69b55e60330e74](https://github.com/Godofbrowser/vuejs-dialog/commit/b511287ca4ec0549927964460b69b55e60330e74)
