### ISSUE TITLE
remove external reference to google font css

### ISSUE THREAD

**Issue by slano** [Godofbrowser/vuejs-dialog#20]
Hello Godofbrowser,

first of all thanks for a great vue package, I find it very useful.

One future request to get rid of a minor annoyance. Is there any chance to remove google fonts api import in the javascript? 

`"@import url(https://fonts.googleapis.com/css?family=Noto+Sans:400,700);"`

If I use vuejs-dialog bundled in my project's single app.js, and try to export a page of such project into .pdf using wkhtmltopdf for example the export fails without a connection to the internet, as wkhtmltopdf is not able to fetch the data from googleapis.com.

Thanks!

**Comment by Godofbrowser** [comment]
Thanks for the commendation @slano , i'm looking at the best possible solution to this issue. Meanwhile, suggestions are welcomed.

**Comment by marekfilip** [comment]
@Godofbrowser thanks for sharing your package. It it very helpful indeed 👍 

I would be very pleased for this feature as well, it would remove problem with "Leverage browser caching" in Google PageSpeed Insights. It is known that Google Fonts cache is set to 24 hours.

**Comment by Godofbrowser** [comment]
External fonts removed @slano @marekfilip . Plugin will inherit the document's font.

**Comment by marekfilip** [comment]
@Godofbrowser thanks for really fast feature! That fixed my problem.

**Comment by Godofbrowser** [comment]
You're welcome.
