### ISSUE TITLE
Clicking outside dialog should cancel

### ISSUE THREAD

**Issue by hjortzen** [Godofbrowser/vuejs-dialog#21]
Hi!
First off: Brilliant dialog! I especially like the directive idea!

A feature request (I'll probably make a workaround for now) however:
Being able to configure if the dialog should close (cancel) when clicking outside the dialog (i.e. when clicking the mask)

Great work!

**Comment by Godofbrowser** [comment]
Thanks @hjortzen 

I also think it'll be nice to have this feature.

**Comment by maxorlovsky** [comment]
It's already there
Vue.use(VueDialog, {
    backdropClose: true
});

**Comment by hjortzen** [comment]
Yeah. I created the pull request that solved this issue.
Closing issue...
