### ISSUE TITLE
Documentation doesn't explain how to open alert

### ISSUE THREAD

**Issue by maxorlovsky** [Godofbrowser/vuejs-dialog#27]
Explanation about alert dialog in readme is missing. I think this.$dialog.alert needs to be added as it's not mentioned anywhere except if you go look at source or docs folders in repo.

**Comment by Godofbrowser** [comment]
@maxorlovsky That's correct. `this.$dialog.alert('The alert message')` opens the alert dialog and it escaped the documentation. Would you like to send a PR fixing that or have me update it in my spare time?
