### ISSUE TITLE
method for prompt ?

### ISSUE THREAD

**Issue by boomhq** [Godofbrowser/vuejs-dialog#29]
Hi,

Thanks for your component it's very useful.
I see on another issue "$dialog.prompt" is still in progress ? 
Have you any information for that  ?

Thanks

**Comment by Godofbrowser** [comment]
@boomhq I'm a little bit occupied at the moment. I'll start working on the prompt method by the end of this month hopefully. I'm glad you find the plugin useful. Thanks for commending.

**Comment by Godofbrowser** [comment]
It's here #48
