### ISSUE TITLE
Custom Component - error

### ISSUE THREAD

**Issue by gmatkowski** [Godofbrowser/vuejs-dialog#35]
Error in created hook: "TypeError: this.$dialog.registerComponent is not a function"

uuups :-)

![image](https://user-images.githubusercontent.com/5032094/42933553-5729b00a-8b45-11e8-8e1d-563e58a04a44.png)

Can you fix it ? :-)

**Comment by Godofbrowser** [comment]
Hello @gmatkowski , please hold let me test

**Comment by gmatkowski** [comment]
sure, I'll wait :-)

**Comment by Godofbrowser** [comment]
@gmatkowski Please be sure your package json file has vuejs-dialog not earlier than v1.0.0

**Comment by gmatkowski** [comment]
I'm sure:
![image](https://user-images.githubusercontent.com/5032094/42935153-34052b96-8b49-11e8-8362-dd35dc62e64c.png)

**Comment by gmatkowski** [comment]
Ok, my bad ... somehow after re npm run watch it works good ... perhaps some cache issue.

**Comment by Godofbrowser** [comment]
Great! i was about sending a fiddle

**Comment by Godofbrowser** [comment]
Closing as it is confirmed to be working [demo](http://jsfiddle.net/godofbrowser/pktL3mjb/)
