### ISSUE TITLE
Nested dialog is closed automatically

### ISSUE THREAD

**Issue by rjurado01** [Godofbrowser/vuejs-dialog#4]
I have this code:

```js
this.$dialog.confirm('Please confirm to continue')
  .then(function() {
    vm.$dialog.alert('Alert');
  })
  .catch(function() {
    console.log('Clicked on cancel')
  });
```

When the dialog is resolved sucessfully and the alert is opened it is also closed automatically.

Example running: https://jsfiddle.net/rjurado/5u9u0bdc/

**Comment by Godofbrowser** [comment]
@rjurado01 Thanks for reporting this issue. Please see fix + improvement: 21c5300481dfae9f682a0addcf1078033a22e8ec

**Comment by rjurado01** [comment]
Thanks it works!!

**Comment by Godofbrowser** [comment]
You're welcome. Thanks for staring ☺️
