### ISSUE TITLE
hi, Excuse me

### ISSUE THREAD

**Issue by awesomezz** [Godofbrowser/vuejs-dialog#9]
How to set only one button ？ thank you

**Comment by Godofbrowser** [comment]
Hello @awesomezz to display only one button you'll need to use the `vm.$dialog.alert()` method instead of `vm.$dialog.confirm()`. it's also possible to place the button on the left hand side of the dialog by setting the reverse option `vm.$dialog.alert('This is an alert', {reverse: true})`

**Comment by awesomezz** [comment]
thank you very much。

发自我的 iPhone

**Comment by awesomezz** [comment]
Thank you very much 

发自我的 iPhone

**Comment by Godofbrowser** [comment]
You're welcome.
